name: webserv CI

on:
  push:
    branches: [ ghactions-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: make
        run: make
