name: webserv CI
run-name: Run make on ${{ github.ref_name	 }}

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04.5
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: make
        run: make
